error handling

diff --git a/Untitled-1.yml b/Untitled-1.yml
--- a/Untitled-1.yml
+++ b/Untitled-1.yml
@@ -24,6 +24,14 @@ Resources:
           !Sub |
               #!/bin/bash
 
+              notify_failure() {
+                echo 'ERROR'
+                /opt/aws/bin/cfn-signal -e 1 --stack=EC2Stack --resource=EC2Instance
+                exit 1
+              }
+
+              trap 'notify_failure' ERR
+
               yum update -y
               yum install -y git
 
@@ -42,7 +50,7 @@ Resources:
 
               sudo -H -u ec2-user bash -c '. ~/.nvm/nvm.sh && nvm install --lts && nvm use --lts && node -v && npm -v'
 
-              sudo -H -u ec2-user bash -c 'git clone https://github.com/chillguire/TEG-Software.git'
+              sudo -H -u ec2-user bash -c 'git clone https://github.com/chillguire/TEG-Software.gitt'
               
               cd TEG-Software
 
